---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        support.contact: "tony.stark@sosckshop.com"
        support.channel: "#support-sockshop-services"
      labels:
        app: orders
        stage: production
        release: stable
        version: "1.1"
        tier: "business"
        product: "sockshop"
    spec:
      containers:
      - name: orders
        image: bacherfl/orders:0.5.0
        env:
        - name: JAVA_OPTS
          value: -Xms128m -Xmx512m -XX:PermSize=128m -XX:MaxPermSize=128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
        - name: DT_TAGS
          value: "dt_tag1=value1"
        - name: DT_CUSTOM_PROP
          value: "CUSTOM_PROP1=VALUE1"
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 400m
            memory: 1024Mi
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
  namespace: production
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: orders
